services:
  php-fpm:
    image: php:7.4-fpm
    container_name: php_fpm
    volumes:
      - ./index.php:/var/www/html/index.php
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.php:/var/www/html/index.php
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app_network:
    external: true
